services:
  igloo-server:
    environment:
      NODE_ENV: production
      IGLOO_SERVER_MODE: prod
    volumes: []

  igloo-web:
    environment:
      NODE_ENV: production
      IGLOO_WEB_MODE: prod
    volumes: []

  igloo-cli:
    environment:
      NODE_ENV: production
      IGLOO_CLI_MODE: prod
    volumes: []
