#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OVERRIDE_FILE="$ROOT_DIR/compose.override.yml"

cat > "$OVERRIDE_FILE" <<OUT
# Auto-generated by scripts/setup-dev.sh
# No additional local repo mounts are configured
# Do not edit manually - re-run setup-dev.sh to regenerate

services: {}
OUT

echo "Generated compose.override.yml"
