#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OVERRIDE_FILE="$ROOT_DIR/compose.override.yml"
REPOS_DIR="$ROOT_DIR/repos"

HAS_BIFROST=false
HAS_IGLOO_CORE=false

if [ -d "$REPOS_DIR/bifrost-ts" ] && [ -n "$(ls -A "$REPOS_DIR/bifrost-ts" 2>/dev/null)" ]; then
  HAS_BIFROST=true
fi
if [ -d "$REPOS_DIR/igloo-core" ] && [ -n "$(ls -A "$REPOS_DIR/igloo-core" 2>/dev/null)" ]; then
  HAS_IGLOO_CORE=true
fi

if [ "$HAS_BIFROST" = false ] && [ "$HAS_IGLOO_CORE" = false ]; then
  cat > "$OVERRIDE_FILE" <<'OUT'
# Auto-generated by scripts/setup-dev.sh
# No local repo mounts available

services: {}
OUT
  echo "No local repo mounts found. Generated empty compose.override.yml"
  exit 0
fi

build_mounts() {
  local mounts=""
  if [ "$HAS_BIFROST" = true ]; then
    mounts="$mounts      - ./repos/bifrost-ts:/app/node_modules/@frostr/bifrost:ro"$'\n'
  fi
  if [ "$HAS_IGLOO_CORE" = true ]; then
    mounts="$mounts      - ./repos/igloo-core:/app/node_modules/@frostr/igloo-core:ro"$'\n'
  fi
  echo -n "$mounts"
}

MOUNTS=$(build_mounts)

cat > "$OVERRIDE_FILE" <<OUT
# Auto-generated by scripts/setup-dev.sh
# Mounts local repos into services for development
# Do not edit manually - re-run setup-dev.sh to regenerate

services:
  igloo-server:
    volumes:
      - ./repos/igloo-server:/app:rw
      - ./data/igloo-server:/app/data:rw
      - ./logs/igloo-server:/app/logs:rw
      - igloo-server-node-modules:/app/node_modules
$MOUNTS
  igloo-web:
    volumes:
      - ./repos/igloo-web:/app:rw
      - ./logs/igloo-web:/app/logs:rw
      - igloo-web-node-modules:/app/node_modules
$MOUNTS
  igloo-cli:
    volumes:
      - ./repos/igloo-cli:/app:rw
      - ./logs/igloo-cli:/app/logs:rw
      - igloo-cli-node-modules:/app/node_modules
$MOUNTS
OUT

echo "Generated compose.override.yml"
